### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by LaplaceSingularity** [Crone1/Sleep-Prediction#1]
Hey mate! Your project's really awesome. Would you mind sharing the dataset? I'm working on an application for prediction stress base on sleep quality(light, rem, deep), but all the data I have will lead to inaccurate results, that's the reason that I looking for more datasets(surprising I could not find too many:)).

**Comment by Crone1** [comment]
Glad you are finding my work useful. I have uploaded the datasets used for this project so you will be able to see it now. This data includes the raw apple watch data cropped to get rid of instances without a sleep label and also includes aggregate features created by the author of the initial paper on her [Github](https://github.com/ojwalch/sleep_classifiers). Hope that helps!
BTW If you are looking for more sleep datasets, you can find some at https://sleepdata.org/datasets.
